#! /usr/bin/env python
# -*- coding: utf-8 -*-
# vim:fenc=utf-8
#
# Copyright © 2019 nicolasfara <nicolas.farabegoli@gmail.com>
#
# Distributed under terms of the MIT license.

"""
Simple script for convert a pdf menu into a PNG.
"""

import os
import argparse
from datetime import date
from PyPDF2 import PdfFileWriter, PdfFileReader, PdfFileMerger
from PyPDF2.pdf import PageObject
from pdf2image import convert_from_path

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("pdf_in")
    args = parser.parse_args()

    reader = PdfFileReader(open(args.pdf_in, 'rb'))
    page_2 = reader.getPage(2)
    page_3 = reader.getPage(3)

    translated_page = PageObject.createBlankPage(None, 2 * page_3.mediaBox.getWidth(), page_3.mediaBox.getHeight())
    translated_page.mergeScaledTranslatedPage(page_3, 1, page_3.mediaBox.getWidth(), 0)

    translated_page.mergePage(page_2)

    writer = PdfFileWriter()
    writer.addPage(translated_page)

    with open('tmp-menu.pdf', 'wb') as f:
        writer.write(f)

    pages = convert_from_path('tmp-menu.pdf')
    for page in pages:
        page.save('menu-' + str(date.today()) + '.png', 'PNG')

    os.remove('tmp-menu.pdf')

if __name__ == "__main__":
    main()
